name: Python CI

on:
  push:
    branches:
      - feature/calculadora_2302692_2303304
  pull_request:
    branches:
      - feature/calculadora_2302692_2303304     
      - main     
  pull_request:
    branches:
      - main        

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python testCalculadora.py