name: Python Application Testes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    - name: Checkout code
      uses: actions/checkout@v

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Run tests
      run: python3 -m unittest .\testes.py

