# .github/workflows/python-app.yml

name: Python Application CI

on:
  push:
    branches:
      - feature/calculadora_2302437_2301076_retificacao
  pull_request:
    branches:
      - feature/calculadora_2302437_2301076_retificacao

jobs:
  test:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          # Caso haja algum pacote extra, você pode instalar aqui
          # pip install -r requirements.txt 

      - name: Run tests
        run: python3 -m unittest calculadora_test.py
